### ISSUE TITLE
Suggestion to show greyed out icon for mounts/pets/items etc, that are not obtained yet vs obtained is colored.

### ISSUE THREAD

**Issue by AODfan** [kevinclement/SimpleArmory#535]
Suggestion to show greyed out icon for mounts/pets/items etc, that are not obtained yet vs obtained is colored.

**Comment by maxdekrieger** [comment]
Thanks for your suggestion!
Personally, I would be interested in a proof of concept, feel free to show an example 😄
My main concern is that this would reduce the difference between the obtained and not-obtained and therefore it would feel less satisfying to complete a new collectible.

**Comment by Urtgard** [comment]
I really like that suggestion. And tried and made a poc:

![image](https://github.com/kevinclement/SimpleArmory/assets/13890391/c98bc9cd-99cc-453e-b07e-6794e1613b49)
![image](https://github.com/kevinclement/SimpleArmory/assets/13890391/4276c695-f940-4ee6-96c8-6b99dcb68693)
![image](https://github.com/kevinclement/SimpleArmory/assets/13890391/fea2a1d2-3476-4fae-87e2-7bec930d8d00)
![simplearmory](https://github.com/kevinclement/SimpleArmory/assets/13890391/6a7708f9-ab79-42b6-9cbd-55fe58f5ddd5)


```css
/* Styles used in this example */
.unknown {
    filter: grayscale(1) opacity(0.2);
    transition: filter .25s ease
}

.unknown:hover {
    filter: grayscale(0) opacity(1);
}
```
